(package "cycle-slash"
         "0.1.0"
         "Cycle through slash, backslash, and double backslash")

(website-url "https://github.com/jcs-elpa/cycle-slash")
(keywords "convenience")

(package-file "cycle-slash.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "28.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
